@startuml

object 管理员{
职工号：0123456789
姓名：张三
权限编号：1
}

object 管理员权限{
编号：1
权限：系统管理、图书管理、借阅管理
}

object 系统配置{
借阅限额：3
借书时间：30天
可续借次数：1
}

object 馆藏书籍资源{
编号：1
书籍名称：信息系统分析与设计
馆藏数量：10
可借数量：10
总借阅量：0
类型编号：1
品种编号：1
}

object 图书品种{
编号：1
ISBN编码：978-7-302-32982-4
作者：王晓敏、邝孔武
价格: 45
简介: 信息系统分析与设计教材
出版社：清华大学出版社
出版日期：2013年8月
版本 4
}

object 图书类型{
编号: 1
名称: 计算机
}

object 资源记录{
流水编号：2019040801
时间：2019-04-08
资源类型编号：1
流水绑定记录编号：1 / 1-1,1-2
}

object 资源类型{
编号：1
名称：书籍
编号：2
名称：借阅
}

object 预定信息{
 预定日期: 2019-4-8
 预定书籍数据编号: 1-1
 预定读者编号：1
 }

object 读者{
借书卡号：201610414422
姓名：肖清宇
身份证号:513258468
已借图书数量:12
逾期次数:2
}

object 借阅记录{
编号: 1
借书日期: 2019-3-8
归还日期: 209-4-7
借阅读者借书卡号：21610414422
登记管理员职工号：0123456789
}

object 逾期记录{
编号: 1
预期天数：3
借阅编号：1
罚款编号：1
罚款：30
}

object 罚款细则{
编号：1
规则规定：逾期3天以内
罚款倍数：1.1
}

note "对象中的书籍数据编号为书籍资源编号和品种编号的组合" as N1
@enduml