@startuml
管理员  --  系统配置:配置
管理员  --  管理员权限:分配
资源记录 <|--  资源类型
馆藏目录 "1"  -- "1.. n" 馆藏书籍资源
馆藏书籍资源 "1" *-- "n" 资源记录:拥有
馆藏书籍资源  "1" *-- "1.. n" 图书品种
馆藏书籍资源  "1" *-- "1.. n" 图书类型
预定信息 "n" -- "1" 读者信息:拥有
资源记录 "1" -- "0.. 1" 预定信息:属于
预定信息 "n" -- "1" 馆藏书籍资源:被预定
资源记录 "1" -- "0.. 1" 借阅记录:属于
资源记录 "1" -- "0.. 1" 逾期记录:属于
借阅记录 "n" -- "1" 读者信息:填写
管理员 "1" -- "n" 借阅记录:登记
逾期记录 "0.. 1" -- "1" 借阅记录
逾期记录 "1" -- "1.. n" 罚款细则:使用
class 管理员{
职工号
姓名
}
class 管理员权限{
权限
}
class 系统配置{
读者可同时借阅书籍限额
借书规定时间
书籍可续借次数
}
class 资源记录{
流水号
时间
}
class 资源类型{
名称
}
class 馆藏目录{

}
class 馆藏书籍资源{
书籍名称
馆藏库存数量
可借数量
总借阅量
}
class 图书类型{
名称
}
class 图书品种{
ISBN编码
作者
价格
简介
出版社
出版日期
版本
}
class 预定信息{
预定日期
预定书籍
}
class 读者信息{
姓名
身份证号
借书卡号
已借图书数量
逾期次数
}

class 借阅记录{
借书日期
归还日期
}
class 逾期记录{
预期天数
}
class 罚款细则{
规则规定
罚款倍数
}
@enduml