@startuml
actor 读者
actor ": 读者" as 读者
participant ": 馆藏目录" as 馆藏目录
participant ": 馆藏书籍资源" as 馆藏书籍资源
skinparam sequenceParticipant underline
activate 读者
读者->馆藏目录:取馆藏目录
activate 馆藏目录
馆藏目录->馆藏图书资源:查询图书资源信息
activate 馆藏图书资源
馆藏图书资源-->读者:返回图书资源信息
deactivate 馆藏图书资源
deactivate 馆藏目录
deactivate 读者
@enduml