@startuml
actor ": 图书管理员" as 图书管理员
participant ": 读者" as 读者
participant ": 馆藏目录" as 馆藏目录
participant ": 馆藏书籍资源" as 馆藏书籍资源
participant ": 借书记录" as 借书记录
skinparam sequenceParticipant underline
activate 图书管理员
图书管理员->读者:验证读者信息
activate 读者
deactivate 读者
loop
opt
图书管理员->借书记录:取读者该图书可续借次数
activate 借书记录
借书记录-->图书管理员:是否可续借
deactivate 借书记录
end
图书管理员->借书记录:输入图书信息查询借书记录
activate 借书记录
借书记录->馆藏书籍资源:取书籍信息
activate 馆藏书籍资源
馆藏书籍资源-->借书记录:读者当前正借阅书籍信息
deactivate 馆藏书籍资源
借书记录-->图书管理员:借书记录
deactivate 借书记录
图书管理员->借书记录:更新预计归还时间
activate 借书记录
deactivate 借书记录
end
图书管理员->借书记录:打印续借清单
activate 借书记录
deactivate 借书记录
deactivate 图书管理员
@enduml