@startuml
usecase (编目)
usecase (图书检索)

usecase (借阅图书)
usecase (借书)
usecase (还书)

usecase (读者查询)
usecase (登陆)
usecase (系统升级)
usecase (验证读者身份)

actor :采编员:
actor :读者:
actor :系统维护员:
actor :图书管理员:
:采编员: --> (编目)
:采编员: --> (图书检索)
:采编员: --> (登陆)

:读者: --> (图书检索)
:读者: --> (借阅图书)
:读者: --> (登陆)

:图书管理员: --> (图书检索)
:图书管理员: --> (借阅图书)
:图书管理员: --> (读者查询)
:图书管理员: --> (登陆)

:系统维护员: --> (系统升级)
:系统维护员: --> (登陆)


(借阅图书) --> (借书) : <<include>>
(借阅图书) --> (还书) : <<include>>

(借书) --> (验证读者身份) : <<include>>
(借书) --> (验证读者身份) : <<include>>
@enduml